# Generated by Django 5.0.4 on 2024-04-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="project_images/")),
                ("url", models.URLField(blank=True)),
                ("date", models.DateField()),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
